// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/getrecipes/{userID}": {
            "get": {
                "description": "Get saved recipes based on userID from MongoDB",
                "produces": [
                    "application/json"
                ],
                "summary": "Get saved recipes based on userID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "userID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SavedRecipeResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.RespMessage"
                        }
                    }
                }
            }
        },
        "/recipe/{id}": {
            "get": {
                "description": "Get recipe information based on given recipe id",
                "produces": [
                    "application/json"
                ],
                "summary": "Get recipe information",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Recipe ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RecipeInfo"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.RespMessage"
                        }
                    }
                }
            }
        },
        "/recipes": {
            "get": {
                "description": "Search recipe based on given query. Example /recipe?query=italian",
                "produces": [
                    "application/json"
                ],
                "summary": "Search recipes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Recipe search by natural language query i.e 'italian with egg'",
                        "name": "query",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RecipeSearchResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.RespMessage"
                        }
                    }
                }
            }
        },
        "/save/{userID}/{recipeID}": {
            "post": {
                "description": "Saves recipe based on userID and recipeID to MongoDB",
                "summary": "Save user's saved recipe",
                "parameters": [
                    {
                        "type": "string",
                        "description": "userID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "recipeID",
                        "name": "recipeID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RespMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.RespMessage"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ExtendedIngredients": {
            "type": "object",
            "properties": {
                "aisle": {
                    "type": "string"
                },
                "amount": {
                    "type": "number"
                },
                "consitency": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "measures": {
                    "$ref": "#/definitions/api.Measures"
                },
                "meta": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "original": {
                    "type": "string"
                },
                "originalName": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "api.Measures": {
            "type": "object",
            "properties": {
                "metric": {
                    "$ref": "#/definitions/api.Metric"
                },
                "us": {
                    "$ref": "#/definitions/api.Metric"
                }
            }
        },
        "api.Metric": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "unitLong": {
                    "type": "string"
                },
                "unitShort": {
                    "type": "string"
                }
            }
        },
        "api.ProductMatch": {
            "type": "object",
            "properties": {
                "averageRating": {
                    "type": "number"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "imageUrl": {
                    "type": "string"
                },
                "link": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "ratingCount": {
                    "type": "number"
                },
                "score": {
                    "type": "number"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "api.Recipe": {
            "type": "object",
            "properties": {
                "calories": {
                    "type": "number"
                },
                "carbs": {
                    "type": "string"
                },
                "fat": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "imageType": {
                    "type": "string"
                },
                "protein": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "api.RecipeInfo": {
            "type": "object",
            "properties": {
                "aggregateLikes": {
                    "type": "integer"
                },
                "analyzedInstructions": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "cheap": {
                    "type": "boolean"
                },
                "creditsText": {
                    "type": "string"
                },
                "cuisines": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "dairyFree": {
                    "type": "boolean"
                },
                "diets": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "dishTypes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "extendedIngredients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.ExtendedIngredients"
                    }
                },
                "gaps": {
                    "type": "string"
                },
                "glutenFree": {
                    "type": "boolean"
                },
                "healthScore": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "imageType": {
                    "type": "string"
                },
                "instructions": {
                    "type": "string"
                },
                "ketogenic": {
                    "type": "boolean"
                },
                "license": {
                    "type": "string"
                },
                "lowFodmap": {
                    "type": "boolean"
                },
                "occasions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "pricePerServing": {
                    "type": "number"
                },
                "readyInMinutes": {
                    "type": "integer"
                },
                "servings": {
                    "type": "number"
                },
                "sourceName": {
                    "type": "string"
                },
                "sourceUrl": {
                    "type": "string"
                },
                "spoonacularScore": {
                    "type": "number"
                },
                "spoonacularSourceUrl": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "sustainable": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                },
                "vegan": {
                    "type": "boolean"
                },
                "vegetarian": {
                    "type": "boolean"
                },
                "veryHealthy": {
                    "type": "boolean"
                },
                "veryPopular": {
                    "type": "boolean"
                },
                "weightWatcherSmartPoints": {
                    "type": "number"
                },
                "whole30": {
                    "type": "boolean"
                },
                "winePairing": {
                    "$ref": "#/definitions/api.WinePairing"
                }
            }
        },
        "api.RecipeMinimal": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "api.RecipeSearchResp": {
            "type": "object",
            "properties": {
                "number": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Recipe"
                    }
                },
                "totalResults": {
                    "type": "integer"
                }
            }
        },
        "api.RespMessage": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "api.SavedRecipeResp": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.RecipeMinimal"
                    }
                }
            }
        },
        "api.WinePairing": {
            "type": "object",
            "properties": {
                "pairedWines": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "pairingText": {
                    "type": "string"
                },
                "productMatches": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.ProductMatch"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "CS411 API",
	Description:      "API for the team's project.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
