// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/recipe": {
            "get": {
                "description": "Search recipe based on given query. Example /recipe?query=italian",
                "produces": [
                    "application/json"
                ],
                "summary": "Search recipe",
                "parameters": [
                    {
                        "type": "string",
                        "description": "recipe search by natural language query i.e 'italian with egg'",
                        "name": "query",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RecipeSearchResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.Recipe": {
            "type": "object",
            "properties": {
                "calories": {
                    "type": "number"
                },
                "carbs": {
                    "type": "string"
                },
                "fat": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "imageType": {
                    "type": "string"
                },
                "protein": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "api.RecipeSearchResp": {
            "type": "object",
            "properties": {
                "number": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Recipe"
                    }
                },
                "totalResults": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "CS411 API",
	Description:      "API for the team's project.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
